name: 'authenticate-with-gh-package-registries'

description: 'An action that adds one or more package sources with credentials to the .nuget config & .npmrc for use with package restores'

inputs:
  read-pkg-token:
    description: 'A personal access token with the read:packages scope that has been authorized for use with each provided org and is from an account that has read access to the repo containing the package.'
    required: true
  read-pkg-token-legacy:
    description: 'A legacy organization personal access token with the read:packages scope that has been authorized for use with each provided org and is from an account that has read access to the repo containing the package.'
    required: false
    default: ''
  orgs:
    description: 'A comma-separated list of organizations that package sources should be added for.'
    required: true
    default: 'wtw-bdoim'
  orgs-legacy:
    description: 'A comma-separated list of legacy organizations that package sources should be added for.'
    required: false
    default: ''
  setup-nuget:
    description: 'Flag indicating whether to set each org as a nuget source.'
    required: false
    default: true
    type: boolean
  setup-npm:
    description: 'Flag indicating whether to set each org as an npm registry.'
    required: false
    default: true
    type: boolean
  nuget-package-source-mapping-pattern:
    description: 'A comma separated list of patterns with org names to use for nuget source mapping. IE my-org:Mktp* . This is the mapping for github packages orgs.'
    required: false
    default: null
  show-config-file-contents:
    description: 'Flag indicating whether to output the contents of the config files to the logs for debugging purposes.'
    required: false
    default: false
    type: boolean

runs:
  using: 'composite'

  steps:
    # nuget **********************
    - name: nuget - add soures (if setup-nuget is true)
      if: inputs.setup-nuget == 'true'
      shell: pwsh
      run: ${{ github.action_path }}/nuget.ps1 -rawOrgs "${{ inputs.orgs }}" -rawOrgsLegacy "${{ inputs.orgs-legacy }}" -runnerOs "${{ runner.os }}" -nugetPackageSourceMappingPattern "${{ inputs.nuget-package-source-mapping-pattern }}"

    # npm ************************
    - name: npm - delete existing authToken (if setup-npm is true)
      if: inputs.setup-npm == 'true'
      shell: pwsh
      run: npm config delete //npm.pkg.github.com/:_authToken
      env:
        # If an env var is used in .npmrc and you try to do anything with it, an error is thrown.
        # Add some placeholders here so we can delete the value so subsequent steps can proceed.
        READ_PACKAGE_TOKEN: 'placeholder'
        READ_PACKAGE_TOKEN_LEGACY: 'placeholder'
        GITHUB_TOKEN: 'placeholder'

    - name: npm - add registries (if setup-npm is true)
      if: inputs.setup-npm == 'true'
      shell: pwsh
      run: ${{ github.action_path }}/npm.ps1 -rawOrgs "${{ inputs.orgs }}" -rawOrgsLegacy "${{ inputs.orgs-legacy }}" -runnerOs "${{ runner.os }}"

    # Both ************************
    - name: Create READ_PACKAGE_TOKEN env variable
      shell: bash
      run: |
        echo "READ_PACKAGE_TOKEN=${{ inputs.read-pkg-token }}" >> $GITHUB_ENV
        echo "READ_PACKAGE_TOKEN_LEGACY=${{ inputs.read-pkg-token-legacy }}" >> $GITHUB_ENV

    - name: Output npmrc file contents for debugging
      if: inputs.setup-npm == 'true' && inputs.show-config-file-contents == 'true'
      continue-on-error: true
      shell: bash
      run: |
        echo "Standard List:"
        npm config list

        echo ""
        echo ""
        echo "Long List:"
        npm config ls -l

    - name: Output nuget config file contents for debugging
      if: inputs.setup-nuget == 'true' && inputs.show-config-file-contents == 'true'
      continue-on-error: true
      shell: bash
      run: |
        text="$(dotnet nuget config paths)"
        # Set space as the delimiter
        #IFS=$'\r\n'
        IFS=''
        delimiter=$'\r\n'
        string=$text$delimiter
        # Read the split words into an array
        # based on space delimiter
        newarray=()
        while [[ $string ]]; do
        newarray+=( "${string%%"$delimiter"*}" )
        string=${string#*"$delimiter"}
        done
        # Print each value of the array by using
        # the loop
        for value in ${newarray[@]}
        do
        echo "$value"
        cat "$value"
        echo ""
        echo ""
        done
