name: 'authenticate-with-gh-package-registries'

description: 'An action that adds one or more package sources with credentials to the .nuget config for use with package restores'

inputs:
  read-pkg-token:
    description: 'A personal access token with the read:packages scope that has been authorized for use with each provided org and is from an account that has write access to the repo containing the package.'
    required: true
  orgs:
    description: 'A comma-separated list of organizations that package sources should be added for.'
    required: true
    default: 'im-client,im-customer-engagement,im-enrollment,im-funding,im-platform,im-practices,bc-swat'

runs:
  using: 'composite'
  steps:
    # Nuget **********************
    - name: nuget - add soures
      shell: pwsh
      run: ${{ github.action_path }}/nuget.ps1 -rawOrgs "${{ inputs.orgs }}" -runnerOs "${{ runner.os }}"

    # NPM ************************
    - name: npm - delete existing authToken
      shell: pwsh
      run: npm config delete //npm.pkg.github.com/:_authToken
      env:
        # If an env var is used in .npmrc and you try to do anything with it, an error is thrown.
        # Add some placeholders here so we can delete the value so subsequent steps can proceed.
        READ_PACKAGE_TOKEN: 'placeholder'
        GITHUB_TOKEN: 'placeholder'

    - name: npm - add registries
      shell: pwsh
      run: ${{ github.action_path }}/npm.ps1 -rawOrgs "${{ inputs.orgs }}" -runnerOs "${{ runner.os }}"

    # All ************************
    - name: Create READ_PACKAGE_TOKEN env variable
      shell: bash
      run: echo "READ_PACKAGE_TOKEN=${{ inputs.read-pkg-token }}" >> $GITHUB_ENV
