name: 'authenticate-with-gh-package-registries'

description: 'An action that adds one or more package sources with credentials to the .nuget config & .npmrc for use with package restores'

inputs:
  read-pkg-token:
    description: 'A personal access token with the read:packages scope that has been authorized for use with each provided org and is from an account that has read access to the repo containing the package.'
    required: true
  orgs:
    description: 'A comma-separated list of organizations that package sources should be added for.'
    required: true
    default: 'im-client,im-customer-engagement,im-enrollment,im-funding,im-platform,im-practices,bc-swat'
  setup-nuget:
    description: 'Flag indicating whether to set each org as a nuget source.'
    required: false
    default: true
    type: boolean
  setup-npm:
    description: 'Flag indicating whether to set each org as an npm registry.'
    required: false
    default: true
    type: boolean
  use-second-github-token:
    description: 'Use the secondary environment variable name (READ_PACKAGE_TOKEN_SECOND) instead of the default (READ_PACKAGE_TOKEN). Helpful when authenticating packages with a token from a second GitHub account.'
    required: false
    default: false
    type: boolean
  show-config-file-contents:
    description: 'Flag indicating whether to output the contents of the config files to the logs for debugging purposes.'
    required: false
    default: false
    type: boolean

runs:
  using: 'composite'

  steps:
    # nuget **********************
    - name: nuget - add soures (if setup-nuget is true)
      if: inputs.setup-nuget == 'true'
      shell: pwsh
      run: ${{ github.action_path }}/nuget.ps1 -rawOrgs "${{ inputs.orgs }}" -runnerOs "${{ runner.os }}" -useSecondGithubToken ${{ inputs.use-second-github-token == 'true' && '$True' || '$False' }}

    # npm ************************
    - name: npm - delete existing authToken (if setup-npm is true)
      if: inputs.setup-npm == 'true'
      shell: pwsh
      run: npm config delete //npm.pkg.github.com/:_authToken
      env:
        # If an env var is used in .npmrc and you try to do anything with it, an error is thrown.
        # Add some placeholders here so we can delete the value so subsequent steps can proceed.
        READ_PACKAGE_TOKEN: 'placeholder'
        READ_PACKAGE_TOKEN_SECOND: 'placeholder'
        GITHUB_TOKEN: 'placeholder'

    - name: npm - add registries (if setup-npm is true)
      if: inputs.setup-npm == 'true'
      shell: pwsh
      run: ${{ github.action_path }}/npm.ps1 -rawOrgs "${{ inputs.orgs }}" -runnerOs "${{ runner.os }}" -useSecondGithubToken ${{ inputs.use-second-github-token == 'true' && '$True' || '$False' }}

    # Both ************************
    - name: Create READ_PACKAGE_TOKEN env variable
      if: ${{ inputs.use-second-github-token != 'true' }}
      shell: bash
      run: echo "READ_PACKAGE_TOKEN=${{ inputs.read-pkg-token }}" >> $GITHUB_ENV

    - name: Create READ_PACKAGE_TOKEN_SECOND env variable
      if: ${{ inputs.use-second-github-token == 'true' }}
      shell: bash
      run: echo "READ_PACKAGE_TOKEN_SECOND=${{ inputs.read-pkg-token }}" >> $GITHUB_ENV

    - name: Output npmrc file contents for debugging
      if: inputs.setup-npm == 'true' && inputs.show-config-file-contents == 'true'
      shell: bash
      run: cat ~/.npmrc

    - name: Output nuget config file contents for debugging
      if: inputs.setup-nuget == 'true' && inputs.show-config-file-contents == 'true'
      shell: bash
      run: cat ~/.nuget/NuGet/NuGet.Config
