name: 'authenticate-with-gh-packages-for-nuget'

description: 'An action that adds one or more package sources with credentials to the .nuget config for use with package restores'

inputs:
  github-token:
    description: 'A personal access token with access to each of the organizations that sources will be added for.  Must have read:packages scope.'
    required: true
  orgs:
    description: 'A comma-separated list of organizations that package sources should be added for.'
    required: true
    default: 'im-client,im-customer-engagement,im-enrollment,im-funding,im-platform,im-practices,bc-swat'

runs:
  using: 'composite'
  steps:
    - shell: pwsh
      run: ${{ github.action_path }}/sources.ps1 -token "${{ inputs.github-token }}" -rawOrgs "${{ inputs.orgs }}" -runnerOs "${{ runner.os }}"
